### ISSUE TITLE
REST api v2 not working with ownCloud 10.0.8

### ISSUE THREAD

**Issue by theScrabi** [mondjunge/bookmarks#4]
The REST API v2 is not responding on 10.0.8 anymore.
Sending the default `GET /apps/bookmarks/public/rest/v2/bookmark` gets me a 404:

![screen shot 2018-05-08 at 09 39 03](https://user-images.githubusercontent.com/1891273/39744172-a8913006-52a3-11e8-81f1-0150172e104c.png)

**Comment by mondjunge** [comment]
I am not using owncloud anymore. The original maintainers switched to nextcloud. I have no time to merge the nextcloud bookmarks APP to owncloud.

**Comment by theScrabi** [comment]
I see this is bad :/

**Comment by theScrabi** [comment]
Can I have write access to this repo please.

**Comment by mondjunge** [comment]
I just granted you push access to this repositiory.

**Comment by theScrabi** [comment]
thx

**Comment by mondjunge** [comment]
I found an old (10.0.2.1) owncloud version on my machine, updated it to 10.0.8 and found the REST API to be still working as expected.

I fixed the export Bug, though.

Problem now is: Something changed with the signing of apps. I get errors when trying to sign, so I won't be able to upload the fix to the marketplace.

Owncloud is dead, I recommend to move on to nextcloud. The migration is hassle free, it is just like a normal ownlcoud update.

**Comment by theScrabi** [comment]
> Owncloud is dead, I recommend to move on to nextcloud. The migration is hassle free, it is just like a normal ownlcoud update.

If ownCloud is dead I must either be a zomby or insane ;D because what I see from me and my co workers it looks pretty alive to me :D. The reason it might seem "dead" is because we are currently trying to clean up and get rid of all the legacy sh** instead of putting a ton of unnecessary/unstable features on top of broken code 🙄 

So what I found out is that after the auth refactor in ownCloud 10.0.8 it is required to not only send the basic auth info but also the oc cookies to get an answer.

@mondjunge is this what you fixed? I will test it later.

**Comment by mondjunge** [comment]
@theScrabi I just removed getTemplatingDefaults from exportresults.php to get the export working again.

All I want is a hassle free self hosted cloud infrastructure. Owncloud removed the "hassle free" some time ago. As a user I don't care about the cleanliness of the code. I want working software and owncloud just does not do the job for me anymore, it was "broken" (as in expected features stopped working and I had to fix them myself) on the last 3 updates I did and then I switched to nextcloud.

**Comment by Heetered** [comment]
Thanks @theScrabi for doing this, really appreciate it.

**Comment by theScrabi** [comment]
> @theScrabi I just removed getTemplatingDefaults from exportresults.php to get the export working again.

I am sorry to say that this didn't fix the problem with the authentication via REST. The problem still persists.
